"""
database.py — Gerencia sessões, personagens e histórico de ações
"""

import json
import os
import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone


class Database:
    """Persistence layer with PostgreSQL (Supabase) and SQLite backends.

    PostgreSQL is selected when ``SUPABASE_DB_URL`` (or ``db_url``) is set.
    There is deliberately no automatic fallback after a PostgreSQL connection
    failure: hiding production outages by writing to a local file loses data.
    """

    def __init__(self, path: str = "dnd.db", db_url: str | None = None):
        self.db_url = db_url or os.getenv("SUPABASE_DB_URL")
        self.path = path
        self.backend = "postgres" if self.db_url else "sqlite"
        self._init()

    @contextmanager
    def _conn(self):
        if self.backend == "postgres":
            try:
                from psycopg.rows import dict_row
                import psycopg
            except ImportError as exc:
                raise RuntimeError(
                    "psycopg is required when SUPABASE_DB_URL is configured"
                ) from exc
            conn = psycopg.connect(self.db_url, row_factory=dict_row)
        else:
            conn = sqlite3.connect(self.path)
            conn.row_factory = sqlite3.Row
        try:
            yield conn
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()

    def _init(self):
        with self._conn() as conn:
            schema = """
                CREATE TABLE IF NOT EXISTS sessoes (
                    chat_id     INTEGER PRIMARY KEY,
                    contexto    TEXT    NOT NULL,
                    criada_em   TEXT    NOT NULL,
                    atualizada_em TEXT  NOT NULL
                );

                CREATE TABLE IF NOT EXISTS personagens (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id     INTEGER NOT NULL,
                    chat_id     INTEGER NOT NULL,
                    nome        TEXT    NOT NULL,
                    classe      TEXT    NOT NULL,
                    raca        TEXT    NOT NULL,
                    atributos   TEXT    NOT NULL,  -- JSON
                    historia    TEXT    NOT NULL,
                    detalhes    TEXT    NOT NULL DEFAULT '',
                    criado_em   TEXT    NOT NULL,
                    UNIQUE(user_id, chat_id)
                );

                CREATE TABLE IF NOT EXISTS acoes (
                    id           INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id      INTEGER NOT NULL,
                    chat_id      INTEGER NOT NULL,
                    acao         TEXT    NOT NULL,
                    resultado    TEXT    NOT NULL,
                    feita_em     TEXT    NOT NULL
                );

                CREATE INDEX IF NOT EXISTS idx_personagens_chat ON personagens(chat_id);
                CREATE INDEX IF NOT EXISTS idx_personagens_user ON personagens(user_id, chat_id);
                CREATE INDEX IF NOT EXISTS idx_acoes_chat ON acoes(chat_id);
            """
            if self.backend == "postgres":
                # Keep the deployed schema compatible with SQLite's public
                # return values (timestamps and attributes are strings).
                schema = schema.replace(
                    "INTEGER PRIMARY KEY AUTOINCREMENT",
                    "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                )
                for statement in schema.split(";"):
                    if statement.strip():
                        conn.execute(statement)
            else:
                conn.executescript(schema)

            # Migração incremental para bancos criados antes do campo detalhes.
            if self.backend == "postgres":
                conn.execute("ALTER TABLE personagens ADD COLUMN IF NOT EXISTS detalhes TEXT NOT NULL DEFAULT ''")
            else:
                columns = {row[1] for row in conn.execute("PRAGMA table_info(personagens)").fetchall()}
                if "detalhes" not in columns:
                    conn.execute("ALTER TABLE personagens ADD COLUMN detalhes TEXT NOT NULL DEFAULT ''")

    # ── Sessões ──────────────────────────────────────────────────────────────

    def criar_sessao(self, chat_id: int, contexto: str, reset: bool = False):
        agora = datetime.now(timezone.utc).isoformat()
        placeholder = "%s" if self.backend == "postgres" else "?"
        with self._conn() as conn:
            conn.execute(f"""
                INSERT INTO sessoes (chat_id, contexto, criada_em, atualizada_em)
                VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder})
                ON CONFLICT(chat_id) DO UPDATE SET
                    contexto=excluded.contexto,
                    criada_em=excluded.criada_em,
                    atualizada_em=excluded.atualizada_em
            """, (chat_id, contexto, agora, agora))
            # A criação da sessão não apaga jogadores por padrão. O reset explícito
            # é reservado para iniciar uma campanha nova e evita que um segundo
            # jogador apague os personagens dos demais.
            if reset:
                conn.execute(
                    f"DELETE FROM personagens WHERE chat_id={placeholder}", (chat_id,)
                )
                conn.execute(f"DELETE FROM acoes WHERE chat_id={placeholder}", (chat_id,))

    def obter_sessao(self, chat_id: int) -> dict | None:
        with self._conn() as conn:
            row = conn.execute(
                f"SELECT * FROM sessoes WHERE chat_id={'%s' if self.backend == 'postgres' else '?'}",
                (chat_id,),
            ).fetchone()
            return dict(row) if row else None

    def atualizar_contexto(self, chat_id: int, novo_contexto: str, contexto_anterior: str | None = None) -> bool:
        with self._conn() as conn:
            p = "%s" if self.backend == "postgres" else "?"
            if contexto_anterior is None:
                cur = conn.execute(f"""
                    UPDATE sessoes SET contexto={p}, atualizada_em={p}
                    WHERE chat_id={p}
                """, (novo_contexto, datetime.now(timezone.utc).isoformat(), chat_id))
            else:
                # Compare-and-set: impede que uma ação concorrente sobrescreva
                # silenciosamente o contexto produzido por outra ação.
                cur = conn.execute(f"""
                    UPDATE sessoes SET contexto={p}, atualizada_em={p}
                    WHERE chat_id={p} AND contexto={p}
                """, (novo_contexto, datetime.now(timezone.utc).isoformat(), chat_id, contexto_anterior))
            return cur.rowcount == 1

    # ── Personagens ──────────────────────────────────────────────────────────

    def salvar_personagem(
        self, user_id: int, chat_id: int,
        nome: str, classe: str, raca: str,
        atributos: dict, historia: str, detalhes: str = ""
    ):
        with self._conn() as conn:
            p = "%s" if self.backend == "postgres" else "?"
            conn.execute(f"""
                INSERT INTO personagens
                    (user_id, chat_id, nome, classe, raca, atributos, historia, detalhes, criado_em)
                VALUES ({p}, {p}, {p}, {p}, {p}, {p}, {p}, {p}, {p})
                ON CONFLICT(user_id, chat_id) DO UPDATE SET
                    nome=excluded.nome, classe=excluded.classe,
                    raca=excluded.raca, atributos=excluded.atributos,
                    historia=excluded.historia, detalhes=excluded.detalhes
            """, (
                user_id, chat_id, nome, classe, raca,
                json.dumps(atributos, ensure_ascii=False),
                historia, detalhes[:4000], datetime.now(timezone.utc).isoformat()
            ))

    def obter_personagem(self, user_id: int, chat_id: int) -> dict | None:
        with self._conn() as conn:
            row = conn.execute(
                f"SELECT * FROM personagens WHERE user_id={'%s' if self.backend == 'postgres' else '?'} "
                f"AND chat_id={'%s' if self.backend == 'postgres' else '?'}",
                (user_id, chat_id)
            ).fetchone()
            if not row:
                return None
            p = dict(row)
            p["atributos"] = json.loads(p["atributos"])
            return p

    def listar_jogadores(self, chat_id: int) -> list[dict]:
        with self._conn() as conn:
            rows = conn.execute(
                f"SELECT * FROM personagens WHERE chat_id={'%s' if self.backend == 'postgres' else '?'}",
                (chat_id,),
            ).fetchall()
            result = []
            for r in rows:
                p = dict(r)
                p["atributos"] = json.loads(p["atributos"])
                result.append(p)
            return result

    # ── Ações / Histórico ─────────────────────────────────────────────────────

    def registrar_acao(self, user_id: int, chat_id: int, acao: str, resultado: str):
        with self._conn() as conn:
            p = "%s" if self.backend == "postgres" else "?"
            conn.execute(f"""
                INSERT INTO acoes (user_id, chat_id, acao, resultado, feita_em)
                VALUES ({p}, {p}, {p}, {p}, {p})
            """, (user_id, chat_id, acao, resultado, datetime.now(timezone.utc).isoformat()))

    def historico_recente(self, chat_id: int, limite: int = 10) -> list[dict]:
        with self._conn() as conn:
            p = "%s" if self.backend == "postgres" else "?"
            rows = conn.execute(f"""
                SELECT a.*, p.nome FROM acoes a
                LEFT JOIN personagens p ON a.user_id=p.user_id AND a.chat_id=p.chat_id
                WHERE a.chat_id={p}
                ORDER BY a.id DESC LIMIT {p}
            """, (chat_id, limite)).fetchall()
            return [dict(r) for r in reversed(rows)]
